apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: leehc114/techtrends:latest
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deploy.containerPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deploy.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends
          resources:
            requests:
              cpu: {{ .Values.deploy.resources.requests.cpu }}
              memory: {{ .Values.deploy.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deploy.resources.limits.cpu }}
              memory: {{ .Values.deploy.resources.limits.memory }}
